version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports: ["15672:15672", "5672:5672"]

  ride_service:
    build: ./ride_service
    ports: ["5002:5002"]
    depends_on: [rabbitmq]

  analytics_service:
    build: ./analytics_service
    depends_on: [rabbitmq]